### ISSUE TITLE
02_glycan_data: ValueError

### ISSUE THREAD

**Issue by dtchang** [BojarLab/glycowork#15]
df_glycan.index = df_glycan.glycan.values.tolist()
AttributeError: 'DataFrame' object has no attribute 'glycan'

**Comment by Bribak** [comment]
Hi, I think you've run this cell from the notebook twice (or at least ran it once before you ran the line you indicated):

```
df_glycan.index = df_glycan.glycan.values.tolist()
df_glycan.drop(['glycan'], axis = 1, inplace = True)
```
As the glycan column is dropped in this cell, it's not possible to assign it to the index afterwards. If you just run
```
from glycowork.glycan_data.loader import df_glycan
df_glycan.index = df_glycan.glycan.values.tolist()
```
it works fine (I've tested it just now in multiple environments).
In general, I'd advise against using the documentation notebooks for modified code, as their main purpose is illustration. You can just import whatever you need in your Python workspace of choice, that should work better on average.

**Comment by dtchang** [comment]
Thanks for the explanation.
