### ISSUE TITLE
Getting an error when using lectinOracle in glycowork 0.8.0

### ISSUE THREAD

**Issue by klarich** [BojarLab/glycowork#27]
Running the lectinOracle example from the glycowork documentation gives the following error:
![Screenshot 2023-08-24 at 2 09 26 PM](https://github.com/BojarLab/glycowork/assets/22804730/d0c47166-7566-4c5f-b0d7-e3b8fdc8b647)

**Comment by klarich** [comment]
The above example does not cause an error with 0.7.0

**Comment by Bribak** [comment]
Thanks for spotting this! When changing lib from a list to a dict, I overlooked that the protein/amino acid-lib (`chars`) also needs to be changed accordingly.
I'm about to head to the airport but I'm planning to make this into a 0.8.1 hotfix next week

**Comment by klarich** [comment]
Awesome, thanks!

**Comment by Bribak** [comment]
It's fixed in #28 ; the PyPI version will be updated soon as well
Thanks again for bringing it up!
