### ISSUE TITLE
Bad IUPAC sequence in glycowork/glycan_data/v9_df_species.csv

### ISSUE THREAD

**Issue by edwardsnj** [BojarLab/glycowork#31]
I found the following bad IUPAC sequence in glycowork/glycan_data/v9_df_species.csv:

GlcNAc(b1-2)Man(a1-?)[Man(a1-?)]Man(b1-4)GlcNAc(b1-4)[Fuc(a1-6)GlcNAc

It is missing a ] just before the reducing end GlcNAc.

- n

**Comment by Bribak** [comment]
Thanks for picking that up! We'll fix it in the root dataset; though that will only roll out with 1.1 as changing the dataset usually causes some downstream changes etc.
