### ISSUE TITLE
Bad IUPAC sequence in glycowork/glycan_data/v9_df_species.csv

### ISSUE THREAD

**Issue by edwardsnj** [BojarLab/glycowork#32]
I found the following bad IUPAC sequence in glycowork/glycan_data/v9_df_species.csv:

{Gal(b1-?)GlcNAc(b1-?)}{Neu5Ac(a2-?)}Gal(b1-4)GlcNAc(b1-2)Man(a1-3)[Gal(b1-4)GlcNAc(b1-2)Man(a1-3)]Man(b1-4)GlcNAc(b1-4)GlcNAc

It has two Man(a1-3) linkages connected to the same Man(b1-4) residue.

- n

**Comment by Bribak** [comment]
Thanks for picking that up! We'll fix it in the root dataset; though that will only roll out with 1.1 as changing the dataset usually causes some downstream changes etc.

**Comment by Bribak** [comment]
Commit 517f3ae has solved this issue and we have put methods in place to prevent that kind of error to enter the database again. The file is already available on the dev branch and will be merged into main soon (hopefully end of the week)
