### ISSUE TITLE
About Model Training

### ISSUE THREAD

**Issue by Qinulinuli** [BojarLab/glycowork#37]
Dear Glycowork
  When I use the SweetNet model for training, the training results of models with the same set of data are not fixed each time.Excuse me, what parameters do I need to fix to ensure that the results of the model are consistent each time.I trained the model with GPU.

**Comment by Bribak** [comment]
Hello,
the usual strategy for this is to fix all random seeds, so something like:

torch.manual_seed(0)
torch.cuda.manual_seed(0)
torch.use_deterministic_algorithms(True)
np.random.seed(0)
random.seed(0)

Note that this will still not fully remove any variation, as stated by PyTorch itself (https://pytorch.org/docs/stable/notes/randomness.html), but should reduce some of it
Also note that the deterministic algorithms might be detrimental to performance

**Comment by Qinulinuli** [comment]
Thank you.The problem has been resolved.

**Comment by Qinulinuli** [comment]
Dear Glycowork
  Sorry, I overlooked an error while using the provided description code.When I run 'torch.use_deterministic_algorithms(True)', the following error occurred：RuntimeError: scatter_add_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.
How can I solve this problem？

**Comment by Bribak** [comment]
I appreciate the difficulty but this is a torch-problem and has nothing to do with glycowork code (i.e., I couldn't do anything about it). I can only direct you to the PyTorch issues to raise this problem, as they are the only ones able to fix it. Otherwise, use the suggested step in the RuntimeError message.
Thanks & all the best

**Comment by Qinulinuli** [comment]
Thank you.
