### ISSUE TITLE
Custom motifs do not work for several functions

### ISSUE THREAD

**Issue by mattias-erhardsson** [BojarLab/glycowork#38]
I've been struggling to make use of custom motifs. Having looked at the code I suspect it might not work for other functions than annotate_dataset(). For example, get_heatmap() does not pass custom_motifs to annotate_dataset(), which maybe was intended to be done with **kwargs? I tested some naive solutions, for example by adding **kwargs to the get_heatmap() call to annotate_dataset(). As another example I tried adding custom_motifs = [] as a variable in get_heatmap() and pass it on to annotate_dataset() with custom_motifs = custom_motifs but this did not work. I believe more thorough changes might be needed to be able to use custom motifs for most functions.

**Comment by Bribak** [comment]
Thanks for spotting it! Fixed it in 7da8ceb so I'll close this but if the issue persists somewhere let me know

**Comment by Bribak** [comment]
Ah you need to have at least two motifs in your heatmap (otherwise it can't calculate a distance matrix). I'll think about including a more informative error message for that. Also, note that I'll soon change the keyword args to be the standard motifs=True as used in the other functions
