### ISSUE TITLE
Special character '-' in index of df input to get_heatmap() throws unintuitive error

### ISSUE THREAD

**Issue by mattias-erhardsson** [BojarLab/glycowork#49]
### Description
When using get_heatmap(), if you input a df that has an index that contains '-' then you will get an error that is difficult to figure out what it means. Other special characters might mess it up too and create the same error, I haven't tested. This is tested on the main branch. A more descriptive error message could be beneficial for the users.

### Code:
```
# Imports
from glycowork.motif.analysis import get_heatmap
import pandas as pd

# Example with dataframe with alphanumerical index without special character
df_no_special = pd.DataFrame({
    'Gal(b1-3)GalNAc': [0.242959, 0.208267, 0.223529, 0.245893, 0.297072],
    'GalOS(b1-3)GalNAc': [0.007172, 0.012267, 0.017346, 0.004030, 0.006302],
    'Gal(b1-3)[Fuc(a1-?)]GalNAc': [0.140820, 0.183320, 0.182716, 0.202931, 0.160700],
    'Fuc(a1-2)Gal(b1-3)GalNAc': [1.811925, 1.782675, 1.249882, 1.189128, 1.221432],
    'Fuc(a1-?)[HexNAc(?1-?)]GalNAc': [0.098392, 0.079560, 0.063288, 0.047380, 0.051726]
}, index=['A1', 'B1', 'C1', 'D1', 'E1'])

print("Heatmap with alphanumeric index:")
get_heatmap(df_no_special, motifs=True)

# Example with dataframe with index that contains '-'
df_with_special = pd.DataFrame({
    'Gal(b1-3)GalNAc': [0.242959, 0.208267, 0.223529, 0.245893, 0.297072],
    'GalOS(b1-3)GalNAc': [0.007172, 0.012267, 0.017346, 0.004030, 0.006302],
    'Gal(b1-3)[Fuc(a1-?)]GalNAc': [0.140820, 0.183320, 0.182716, 0.202931, 0.160700],
    'Fuc(a1-2)Gal(b1-3)GalNAc': [1.811925, 1.782675, 1.249882, 1.189128, 1.221432],
    'Fuc(a1-?)[HexNAc(?1-?)]GalNAc': [0.098392, 0.079560, 0.063288, 0.047380, 0.051726]
}, index=['A-1', 'B-1', 'C-1', 'D-1', 'E-1'])

print("Heatmap with special character index:")
get_heatmap(df_with_special, motifs=True)
```
### Error:

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> Cell In[87], line 29
>      27 # Example with character index
>      28 print("Heatmap with Character Index:")
> ---> 29 get_heatmap(df_with_special, motifs=True)
> 
> File [~\AppData\Local\Programs\Python\Python312\Lib\site-packages\glycowork\motif\analysis.py:214](http://localhost:8888/lab/tree/~/AppData/Local/Programs/Python/Python312/Lib/site-packages/glycowork/motif/analysis.py#line=213), in get_heatmap(df, motifs, feature_set, transform, datatype, rarity_filter, filepath, index_col, custom_motifs, return_plot, **kwargs)
>     212 df = df.dropna(axis = 1)
>     213 if motifs:
> --> 214   df = clean_up_heatmap(df.T)
>     215 if not (df < 0).any().any():
>     216   df /= df.sum()
> 
> Cell In[61], line 36, in debug_clean_up_heatmap(df)
>      34 max_idx_series = grouped.apply(lambda group: group.index.to_series().str.len().idxmax())
>      35 print("max_idx_series:", max_idx_series)
> ---> 36 result = df.loc[max_idx_series].drop_duplicates()
>      37 print("Result DataFrame after cleanup:")
>      38 print(result)
> 
> File [~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\indexing.py:1191](http://localhost:8888/lab/tree/~/AppData/Local/Programs/Python/Python312/Lib/site-packages/pandas/core/indexing.py#line=1190), in _LocationIndexer.__getitem__(self, key)
>    1189 maybe_callable = com.apply_if_callable(key, self.obj)
>    1190 maybe_callable = self._check_deprecated_callable_usage(key, maybe_callable)
> -> 1191 return self._getitem_axis(maybe_callable, axis=axis)
> 
> File [~\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\indexing.py:1418](http://localhost:8888/lab/tree/~/AppData/Local/Programs/Python/Python312/Lib/site-packages/pandas/core/indexing.py#line=1417), in _LocIndexer._getitem_axis(self, key, axis)
>    1416 if not (isinstance(key, tuple) and isinstance(labels, MultiIndex)):
>    1417     if hasattr(key, "ndim") and key.ndim > 1:
> -> 1418         raise ValueError("Cannot index with multidimensional key")
>    1420     return self._getitem_iterable(key, axis=axis)
>    1422 # nested tuple slicing
> 
> ValueError: Cannot index with multidimensional key

**Comment by Bribak** [comment]
That one's funny, thanks:D At some point I inputted things in the wrong orientation into get_heatmap, so I made it such that the function would simply transpose things if the orientation is wrong. But the orientation is detected by checking whether the index looks like a glycan (e.g., containing '-' :D)

I've now fixed it on dev (c68fcd2), by making it less prone to say the index is a glycan. Your example works now
