### ISSUE TITLE
Incorrect error when using exhaustive feature set

### ISSUE THREAD

**Issue by mattias-erhardsson** [BojarLab/glycowork#55]
Running latest dev commit https://github.com/BojarLab/glycowork/commit/db6c19d12088e44a68df6c6335b10e6972ac2c91

The error "Warning: ['exhaustive'] not recognized as features." comes up when using exhaustive as a feature set. I cannot grasp why by looking at the code and it seems to otherwise work as expected. Sample code below.

```
from glycowork.motif.annotate import annotate_dataset
```

```
annotate_dataset(glycans = ['Gal(b1-3)GalNAc', 
                            'GalOS(b1-3)GalNAc', 
                            'Gal(b1-3)[Fuc(a1-?)]GalNAc', 
                            'GlcNAc(b1-2)Man(a1-3)Man', 
                            'Man(a1-6)[Man(a1-3)]Man(b1-4)GlcNAc(b1-4)GlcNAc', 
                            'Neu5Ac(a2-6)Gal(b1-4)GlcNAc(b1-2)Man', 
                            'Neu5Ac(a2-3)Gal(b1-3)GalNAc'],
                feature_set = ['exhaustive'])
```

**Comment by Bribak** [comment]
Ah, that's because I forgot to add 'exhaustive' to the list of permitted feature_set arguments (everything would still be executed correctly but the warning incorrectly announced it) 😅 

Fixed in 64ad05f
